name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/budgetboss
          docker buildx build \
            --file Dockerfile \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            --build-arg MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }} \
            --build-arg MONGO_USER=${{ secrets.MONGO_USER }} \
            --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --build-arg SENDER_EMAIL_ID=${{ secrets.SENDER_EMAIL_ID }} \
            --build-arg SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }} \
            --build-arg TG_API_ID=${{ secrets.TG_API_ID }} \
            --build-arg TG_API_HASH=${{ secrets.TG_API_HASH }} \
            .

          # Tag the same image with 'latest'
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

          # Push the epoch tagged image
          docker push $IMAGE_NAME:$IMAGE_TAG

          # Push the 'latest' tagged image
          docker push $IMAGE_NAME:latest
